feature: UserIdentity implemented  with properties files
user.properties read in the keys repository (to be rebranded)

diff --git a/client/src/main/bash/utils b/client/src/main/bash/utils
--- a/client/src/main/bash/utils
+++ b/client/src/main/bash/utils
@@ -1,3 +1,5 @@
+shopt -s compat31
+
 function _getRemote {
 	remote=$(git config --get magrit.remote)
 	if [[ "$remote" == "" ]]; then
@@ -43,7 +45,7 @@ function _sendSshCommand {
 	host=${_target[$_HOST]}
 	port=${_target[$_PORT]}
 	
-	ssh -x -p $port $user@$host $*
+	ssh -x -p $port $user@$host $* || echo "ssh error: $?"
 }
 
 function _sendSshCommandBg {
